---
apiVersion: v2
name: tssc-tpa
description: TSSC Trusted Profile Analyzer
type: application
version: 1.5.0
appVersion: "2.0.1"
dependencies:
  - name: redhat-trusted-profile-analyzer
    version: 1.0.1
    condition: trustedProfileAnalyzer.enabled
